### ISSUE TITLE
wrong LICENSE

### ISSUE THREAD

**Issue by danielinux** [kaizoku-oh/wolfboot-iar-example#1]
please correct your LICENSE file. Files in this repository are covered by GPL2 as this project is a derivative of https://github.com/wolfSSL/wolfBoot

**Comment by bayrem-gharsellaoui** [comment]
Done, see [b233549](https://github.com/kaizoku-oh/wolfboot-iar-example/commit/b233549a9a70d416ff679dcaf56080d2de4508c0)
